name: Build Patched WAR File

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: checkout xnat-web
      uses: actions/checkout@v2
      with:
        ref: 'releases/1.8.2.2'
    - name: checkout xnat-build
      uses: actions/checkout@v2
      with:
        repository: Australian-Imaging-Service/xnat-build
        path: './xnat-build' 
    - name: hack gradle file
      # Without this hack, the gradle build will fail with a NullPointerException
      run: sed -i 's/IllegalArgumentException/IllegalArgumentException|NullPointerException/g' $GITHUB_WORKSPACE/build.gradle
    - name: patch xnat-web
      run: patch -p1 < "$GITHUB_WORKSPACE/xnat-build/patches/xnat-web_aaf.patch"
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Gradle
      run: gradle --stacktrace clean war
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: 1.8.2.2-ais
        tag_name: release-1.8.2.2-ais
        draft: false
        prerelease: false
        files: ./build/libs/xnat-web-*.war
